---
deployment:
  tasks:
    # ============================================
    # SIMPLE STRAPI CMS DEPLOYMENT
    # ============================================
    - export DEPLOYPATH=/home/leqtaco1/strapi_cms
    - export NODE_VERSION=20

    - echo "=========================================="
    - echo "Deploying Strapi CMS"
    - echo "Timestamp:" $(date)
    - echo "=========================================="

    # Activate Node.js virtual environment
    - echo "Activating Node.js ${NODE_VERSION} virtual environment..."
    - source /home/leqtaco1/nodevenv/strapi_cms/${NODE_VERSION}/bin/activate
    - echo "Node.js version:" $(node --version)
    - echo "npm version:" $(npm --version)
    - echo ""

    # Create deployment directory first
    - mkdir -p $DEPLOYPATH

    # Navigate to Strapi directory
    - cd my-blog-cms

    # Copy source files only (NOT node_modules or build artifacts)
    - echo "Copying source files..."
    - /bin/cp -R config $DEPLOYPATH/
    - /bin/cp -R src $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp tsconfig.json $DEPLOYPATH/ 2>/dev/null || true


    # Navigate to deployment directory
    - cd $DEPLOYPATH

    # Install dependencies in destination
    - echo "Installing dependencies in deployment directory..."
    - npm ci --production

    # Build Strapi in destination
    - echo "Building Strapi admin panel..."
    - export NODE_ENV=production
    - npm run build

    # Create necessary runtime directories
    - mkdir -p $DEPLOYPATH/.cache
    - mkdir -p $DEPLOYPATH/.tmp
    - mkdir -p $DEPLOYPATH/public/uploads

    # Set permissions
    - chmod -R 755 $DEPLOYPATH
    - chmod 600 $DEPLOYPATH/.env 2>/dev/null || true

    - echo "=========================================="
    - echo "Deployment completed successfully!"
    - echo "Files deployed to: $DEPLOYPATH"
    - echo ""
    - echo "NEXT STEPS:"
    - echo "1. Verify .env file exists at: $DEPLOYPATH/.env"
    - echo "2. Setup Node.js app in cPanel:"
    - echo "   - Application Root: $DEPLOYPATH"
    - echo "   - Application Startup File: node_modules/@strapi/strapi/bin/strapi.js"
    - echo "   - Click 'Setup' and 'Start'"
    - echo "3. Access admin: http://cms.leqta.com/admin"
    - echo "=========================================="
