---
deployment:
  tasks:
    # ============================================
    # SIMPLE STRAPI CMS DEPLOYMENT
    # ============================================
    # Update this path for your environment
    - export DEPLOYPATH=/home/leqtaco1/public_html/cms.leqta.com

    - echo "=========================================="
    - echo "Deploying Strapi CMS"
    - echo "Timestamp:" $(date)
    - echo "=========================================="

    # Navigate to Strapi directory
    - cd my-blog-cms

    # Install dependencies
    - echo "Installing dependencies......"
  

    # Build Strapi admin panel
    - echo "Building Strapi..."
    - export NODE_ENV=production


    # Create deployment directory
    - mkdir -p $DEPLOYPATH/public/uploads
    - mkdir -p $DEPLOYPATH
