import { FAQ } from "@/lib/strapi";

export const defaultFAQs: FAQ[] = [
    {
        id: 1,
        documentId: "default-1",
        question: "How does a subscription-based marketing service work?",
        answer: "With our model, you pay a flat monthly fee for continuous marketing support. No contracts, no hidden fees—just expert marketing services tailored to your business needs.",
        category: "general",
        featured: true,
        order: 1,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 2,
        documentId: "default-2",
        question: "What's included in the subscription?",
        answer: "Our subscription includes comprehensive marketing strategy development, content creation, social media management, email marketing campaigns, SEO optimization, performance analytics, and dedicated account management. You'll have access to our full team of marketing experts.",
        category: "services",
        featured: true,
        order: 2,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 3,
        documentId: "default-3",
        question: "Can I upgrade or change my plan?",
        answer: "Absolutely! You can upgrade, downgrade, or modify your plan at any time. Changes take effect immediately, and we'll prorate any billing adjustments. Our flexible approach means you're never locked into a plan that doesn't fit your evolving needs.",
        category: "billing",
        featured: true,
        order: 3,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 4,
        documentId: "default-4",
        question: "How quickly will I see results?",
        answer: "While marketing is a long-term investment, many clients start seeing improvements in their online presence within the first 30 days. Significant results typically become apparent within 3-6 months, depending on your industry, competition, and current market position.",
        category: "results",
        featured: true,
        order: 4,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 5,
        documentId: "default-5",
        question: "Do you work with businesses in my industry?",
        answer: "We have experience across a wide range of industries including technology, healthcare, e-commerce, professional services, and more. Our team adapts our strategies to fit your specific industry requirements and target audience.",
        category: "general",
        featured: true,
        order: 5,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 6,
        documentId: "default-6",
        question: "What makes your approach different?",
        answer: "Our subscription model eliminates the unpredictability of traditional agency pricing. You get consistent, high-quality marketing support without surprise costs or long-term contracts. Plus, our team becomes an extension of your business, learning your brand inside and out.",
        category: "approach",
        featured: true,
        order: 6,
        publishedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];